export const IMG_CDN =
	"https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill";
export const FETCH_MENU_URL =
	"https://www.swiggy.com/dapi/menu/v4/full?lat=31.226736&lng=75.778295&menuId=";

export const restaurantList = [
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "256400",
			name: "Subway",
			uuid: "bbb9c75d-a552-4b27-a3f2-27bc8f0d80e3",
			city: "128",
			area: "Ranipur",
			totalRatingsString: "100+ ratings",
			cloudinaryImageId: "vp0lplx6krq8pzn49bbt",
			cuisines: [
				"Healthy Food",
				"Salads",
				"Snacks",
				"Desserts",
				"Beverages",
			],
			tags: [],
			costForTwo: 35000,
			costForTwoString: "₹350 FOR TWO",
			deliveryTime: 39,
			minDeliveryTime: 39,
			maxDeliveryTime: 39,
			slaString: "39 MINS",
			lastMileTravel: 4.099999904632568,
			slugs: {
				restaurant: "subway-phagwara-central-phagwara-central",
				city: "phagwara",
			},
			cityState: "128",
			address:
				"Chandigarh Highway Plaza, Phagwara Mohali Expy, Phagwara, Punjab 144401",
			locality: "Phagwara Central",
			parentId: 2,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 2400,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 2400,
				message: "",
				title: "Delivery Charge",
				amount: "2400",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID:
				"cid=5729450~p=1~eid=00000185-b937-3d20-41e3-623200190112",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4 kms",
			hasSurge: false,
			sla: {
				restaurantId: "256400",
				deliveryTime: 39,
				minDeliveryTime: 39,
				maxDeliveryTime: 39,
				lastMileTravel: 4.099999904632568,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "3.6",
			totalRatings: 100,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "214083",
			name: "Big 7 Food Plaza",
			uuid: "d3f1c7a4-7687-42a7-a869-b2b7f953e2c2",
			city: "128",
			area: "Hargobind Nagar",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "hmkfi1mryrmmgtw93beg",
			cuisines: ["Beverages", "Mughlai", "North Indian", "Snacks"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 27,
			minDeliveryTime: 27,
			maxDeliveryTime: 27,
			slaString: "27 MINS",
			lastMileTravel: 1.2999999523162842,
			slugs: {
				restaurant:
					"big-7-food-plaza-phagwara-central-phagwara-central",
				city: "phagwara",
			},
			cityState: "128",
			address:
				"Big7foodplaza By Royal Treat, Hargobind Nagar, Phagwara, Punjab, India",
			locality: "Phagwara Central",
			parentId: 45424,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "60% off",
				shortDescriptionList: [
					{
						meta: "60% off | Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "60% off up to ₹120 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "60% OFF",
				shortDescriptionList: [
					{
						meta: "Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "60% off up to ₹120 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 2000,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 500,
						message: "",
					},
				],
				totalFees: 2500,
				message: "",
				title: "Delivery Charge",
				amount: "2500",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.2 kms",
			hasSurge: false,
			sla: {
				restaurantId: "214083",
				deliveryTime: 27,
				minDeliveryTime: 27,
				maxDeliveryTime: 27,
				lastMileTravel: 1.2999999523162842,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.0",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
		crouton: {
			type: "SPECIAL",
			metaInfo: {
				bgColor: "#282C3F",
				icon: "surge_listing_piuzrv",
				textColor: "#ffffff",
				title: "High Demand",
				message: "Surge fee of Rs ₹5 may be applicable",
			},
		},
	},
];
